#!/usr/bin/env python

import rospy
import sys
import cv2
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError

# Create a translator object to convert images
converter = CvBridge()

# A counter to make image names unique
counter = 0

def callback(input):
    # This function receives an image message, translates it into a cv2 image, and saves that image to disk.
    global counter
    counter+=1

    # Translate Image message into a cv2 image using bgr8 encoding.
    cv_image = converter.imgmsg_to_cv2(input,"bgr8")

    # Write the image to disk as a .jpg
    s = "mill_cam_" + str(counter) + ".jpg"
    cv2.imwrite(s,cv_image)





def main():
    # Initialize the ROS node and Subscriber
    rospy.init_node("image_saver_node")
    rospy.Subscriber('raw_image',Image,callback)

    # Spin until shut down
    rospy.spin()





if __name__ == '__main__':
    main()
